<a href="https://colab.research.google.com/github/JuanReyesAn/Data-Science-Portfolio-C21/blob/main/ABQ_Weather_2020_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import numpy as np
import glob
import os

from google.colab import userdata, files, drive
drive.mount('/content/drive')

Mounted at /content/drive

In [10]:

# 4 urls each with the same kind of data just different years. i will be concatinating them

In [26]:
url1 = '/content/2025 abq weather.csv'
url2 = '/content/weather 2023-2024.csv'
url3 = '/content/weather 2021-2022.csv'
url4 = '/content/weather 2020.csv'

In [32]:
urls = [
  '/content/2025 abq weather.csv',
  '/content/weather 2023-2024.csv',
  '/content/weather 2021-2022.csv',
  '/content/weather 2020.csv'
]

# Read each CSV and combine them into one DataFrame
weather_df = pd.concat([pd.read_csv(url, low_memory=False) for url in urls], ignore_index=True)

In [34]:
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 369800 entries, 0 to 369799
Data columns (total 70 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   STATION          369800 non-null  object
 1   NAME             369800 non-null  object
 2   LATITUDE         369800 non-null  float64
 3   LONGITUDE        369800 non-null  float64
 4   ELEVATION        369273 non-null  float64
 5   DATE             369800 non-null  object
 6   AWND             2117 non-null    float64
 7   AWND_ATTRIBUTES  2117 non-null    object
 8   DAPR             3827 non-null    float64
 9   DAPR_ATTRIBUTES  3827 non-null    object
 10  EVAP             3102 non-null    float64
 11  EVAP_ATTRIBUTES  3102 non-null    object
 12  MDPR             3795 non-null    float64
 13  MDPR_ATTRIBUTES  3795 non-null    object
 14  MNPN             1143 non-null    float64
 15  MNPN_ATTRIBUTES  1143 non-null    object
 16  MXPN             1143 non-null    float64
 17  MXPN_ATTRIBUTES  1143 non-null    object
 18  PGTM             64 non-null      float64
 19  PGTM_ATTRIBUTES  64 non-null      object
 20  PRCP             364802 non-null  float64
 21  PRCP_ATTRIBUTES  364802 non-null  object
 22  SN32             2192 non-null    float64
 23  SN32_ATTRIBUTES  2192 non-null    object
 24  SNOW             283619 non-null  float64
 25  SNOW_ATTRIBUTES  283619 non-null  object
 26  SNWD             49997 non-null   float64
 27  SNWD_ATTRIBUTES  49997 non-null   object
 28  SX32             2192 non-null    float64
 29  SX32_ATTRIBUTES  2192 non-null    object
 30  TAVG             0 non-null       float64
 31  TAVG_ATTRIBUTES  0 non-null       float64
 32  TMAX             19974 non-null   float64
 33  TMAX_ATTRIBUTES  19974 non-null   object
 34  TMIN             19979 non-null   float64
 35  TMIN_ATTRIBUTES  19979 non-null   object
 36  TOBS             14532 non-null   float64
 37  TOBS_ATTRIBUTES  14532 non-null   object
 38  WDF2             2119 non-null    float64
 39  WDF2_ATTRIBUTES  2119 non-null    object
 40  WDF5             2119 non-null    float64
 41  WDF5_ATTRIBUTES  2119 non-null    object
 42  WESD             17713 non-null   float64
 43  WESD_ATTRIBUTES  17713 non-null   object
 44  WESF             20661 non-null   float64
 45  WESF_ATTRIBUTES  20661 non-null   object
 46  WSF2             2119 non-null    float64
 47  WSF2_ATTRIBUTES  2119 non-null    object
 48  WSF5             2119 non-null    float64
 49  WSF5_ATTRIBUTES  2119 non-null    object
 50  WT01             171 non-null     float64
 51  WT01_ATTRIBUTES  171 non-null     object
 52  WT02             26 non-null      float64
 53  WT02_ATTRIBUTES  26 non-null      object
 54  WT03             410 non-null     float64
 55  WT03_ATTRIBUTES  410 non-null     object
 56  WT04             5 non-null       float64
 57  WT04_ATTRIBUTES  5 non-null       object
 58  WT05             35 non-null      float64
 59  WT05_ATTRIBUTES  35 non-null      object
 60  WT07             22 non-null      float64
 61  WT07_ATTRIBUTES  22 non-null      object
 62  WT08             187 non-null     float64
 63  WT08_ATTRIBUTES  187 non-null     object
 64  WT11             68 non-null      float64
 65  WT11_ATTRIBUTES  68 non-null      object
 66  WT09             7 non-null       float64
 67  WT09_ATTRIBUTES  7 non-null       object
 68  WT06             2 non-null       float64
 69  WT06_ATTRIBUTES  2 non-null       object
dtypes: float64(36), object(34)
memory usage: 197.5+ MB

In [35]:
weather_df.columns.tolist()

['STATION',
 'NAME',
 'LATITUDE',
 'LONGITUDE',
 'ELEVATION',
 'DATE',
 'AWND',
 'AWND_ATTRIBUTES',
 'DAPR',
 'DAPR_ATTRIBUTES',
 'EVAP',
 'EVAP_ATTRIBUTES',
 'MDPR',
 'MDPR_ATTRIBUTES',
 'MNPN',
 'MNPN_ATTRIBUTES',
 'MXPN',
 'MXPN_ATTRIBUTES',
 'PGTM',
 'PGTM_ATTRIBUTES',
 'PRCP',
 'PRCP_ATTRIBUTES',
 'SN32',
 'SN32_ATTRIBUTES',
 'SNOW',
 'SNOW_ATTRIBUTES',
 'SNWD',
 'SNWD_ATTRIBUTES',
 'SX32',
 'SX32_ATTRIBUTES',
 'TAVG',
 'TAVG_ATTRIBUTES',
 'TMAX',
 'TMAX_ATTRIBUTES',
 'TMIN',
 'TMIN_ATTRIBUTES',
 'TOBS',
 'TOBS_ATTRIBUTES',
 'WDF2',
 'WDF2_ATTRIBUTES',
 'WDF5',
 'WDF5_ATTRIBUTES',
 'WESD',
 'WESD_ATTRIBUTES',
 'WESF',
 'WESF_ATTRIBUTES',
 'WSF2',
 'WSF2_ATTRIBUTES',
 'WSF5',
 'WSF5_ATTRIBUTES',
 'WT01',
 'WT01_ATTRIBUTES',
 'WT02',
 'WT02_ATTRIBUTES',
 'WT03',
 'WT03_ATTRIBUTES',
 'WT04',
 'WT04_ATTRIBUTES',
 'WT05',
 'WT05_ATTRIBUTES',
 'WT07',
 'WT07_ATTRIBUTES',
 'WT08',
 'WT08_ATTRIBUTES',
 'WT11',
 'WT11_ATTRIBUTES',
 'WT09',
 'WT09_ATTRIBUTES',
 'WT06',
 'WT06_ATTRIBUTES']

In [36]:
# we got a lot of nulls and stattions that we do not need for now
pd.set_option('display.max_columns', None)

# Display the first 5 rows with every column visible
weather_df.head(5)

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,AWND,AWND_ATTRIBUTES,DAPR,DAPR_ATTRIBUTES,EVAP,EVAP_ATTRIBUTES,MDPR,MDPR_ATTRIBUTES,MNPN,MNPN_ATTRIBUTES,MXPN,MXPN_ATTRIBUTES,PGTM,PGTM_ATTRIBUTES,PRCP,PRCP_ATTRIBUTES,SN32,SN32_ATTRIBUTES,SNOW,SNOW_ATTRIBUTES,SNWD,SNWD_ATTRIBUTES,SX32,SX32_ATTRIBUTES,TAVG,TAVG_ATTRIBUTES,TMAX,TMAX_ATTRIBUTES,TMIN,TMIN_ATTRIBUTES,TOBS,TOBS_ATTRIBUTES,WDF2,WDF2_ATTRIBUTES,WDF5,WDF5_ATTRIBUTES,WESD,WESD_ATTRIBUTES,WESF,WESF_ATTRIBUTES,WSF2,WSF2_ATTRIBUTES,WSF5,WSF5_ATTRIBUTES,WT01,WT01_ATTRIBUTES,WT02,WT02_ATTRIBUTES,WT03,WT03_ATTRIBUTES,WT04,WT04_ATTRIBUTES,WT05,WT05_ATTRIBUTES,WT07,WT07_ATTRIBUTES,WT08,WT08_ATTRIBUTES,WT11,WT11_ATTRIBUTES,WT09,WT09_ATTRIBUTES,WT06,WT06_ATTRIBUTES
0,US1NMSF0050,"EDGEWOOD 2.7 W, NM US",35.0908,-106.2212,2017.8,2025-01-02,NaN,NaN,10.0,",,N",NaN,NaN,0.0,",,N",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,US1NMSF0050,"EDGEWOOD 2.7 W, NM US",35.0908,-106.2212,2017.8,2025-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,",,N",NaN,NaN,0.0,",,N",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,US1NMSF0050,"EDGEWOOD 2.7 W, NM US",35.0908,-106.2212,2017.8,2025-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,",,N",NaN,NaN,0.0,",,N",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,US1NMSF0050,"EDGEWOOD 2.7 W, NM US",35.0908,-106.2212,2017.8,2025-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,",,N",NaN,NaN,0.0,",,N",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,US1NMSF0050,"EDGEWOOD 2.7 W, NM US",35.0908,-106.2212,2017.8,2025-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,",,N",NaN,NaN,0.0,",,N",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
# looking for sunport station
weather_df[['STATION', 'NAME']].value_counts()

STATION      NAME
USW00023050  ALBUQUERQUE INTERNATIONAL AIRPORT, NM US    2192
USC00297481  RIO RANCHO NUMBER 2, NM US                  2192
USC00297477  RIO RANCHO NUMBER 1, NM US                  2192
US1NMVL0037  PERALTA 0.6 S, NM US                        2192
US1NMBR0139  ALBUQUERQUE 3.5 NNE, NM US                  2192
                                                         ...
US1NMBR0479  ALBUQUERQUE 4.0 SSE, NM US                    15
US1NMBR0196  ALBUQUERQUE 6.2 E, NM US                      11
US1NMBR0011  ALBUQUERQUE 8 ENE, NM US                       2
US1NMSN0047  CORRALES 1.6 SSW, NM US                        1
US1NMVL0035  LOS LUNAS 4.6 SE, NM US                        1
Name: count, Length: 316, dtype: int64

In [38]:
# specifically looking at the temperature in sunport/Albuquerque, NM
filter = (weather_df['STATION'] == 'USW00023050')
weather_df[filter]

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,AWND,AWND_ATTRIBUTES,DAPR,DAPR_ATTRIBUTES,EVAP,EVAP_ATTRIBUTES,MDPR,MDPR_ATTRIBUTES,MNPN,MNPN_ATTRIBUTES,MXPN,MXPN_ATTRIBUTES,PGTM,PGTM_ATTRIBUTES,PRCP,PRCP_ATTRIBUTES,SN32,SN32_ATTRIBUTES,SNOW,SNOW_ATTRIBUTES,SNWD,SNWD_ATTRIBUTES,SX32,SX32_ATTRIBUTES,TAVG,TAVG_ATTRIBUTES,TMAX,TMAX_ATTRIBUTES,TMIN,TMIN_ATTRIBUTES,TOBS,TOBS_ATTRIBUTES,WDF2,WDF2_ATTRIBUTES,WDF5,WDF5_ATTRIBUTES,WESD,WESD_ATTRIBUTES,WESF,WESF_ATTRIBUTES,WSF2,WSF2_ATTRIBUTES,WSF5,WSF5_ATTRIBUTES,WT01,WT01_ATTRIBUTES,WT02,WT02_ATTRIBUTES,WT03,WT03_ATTRIBUTES,WT04,WT04_ATTRIBUTES,WT05,WT05_ATTRIBUTES,WT07,WT07_ATTRIBUTES,WT08,WT08_ATTRIBUTES,WT11,WT11_ATTRIBUTES,WT09,WT09_ATTRIBUTES,WT06,WT06_ATTRIBUTES
1860,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-01-01,3.36,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,210.0,",,W",0.0,",,W,0700",NaN,NaN,0.0,",,1,0700",0.0,",,1,0700",NaN,NaN,NaN,NaN,51.0,",,W",25.0,",,W",NaN,NaN,360.0,",,W",10.0,",,W",NaN,NaN,NaN,NaN,14.1,",,W",18.1,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1861,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-01-02,3.58,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1546.0,",,W",0.0,",,W,0700",NaN,NaN,0.0,",,1,0700",0.0,",,1,0700",NaN,NaN,NaN,NaN,61.0,",,W",28.0,",,W",NaN,NaN,340.0,",,W",360.0,",,W",NaN,NaN,NaN,NaN,15.0,",,W",21.9,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1862,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-01-03,3.36,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1519.0,",,W",0.0,",,W,0700",NaN,NaN,0.0,",,1,0700",0.0,",,1,0700",NaN,NaN,NaN,NaN,57.0,",,W",30.0,",,W",NaN,NaN,110.0,",,W",190.0,",,W",NaN,NaN,NaN,NaN,10.1,",,W",12.1,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1863,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-01-04,10.51,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1530.0,",,W",0.0,",,W,0700",NaN,NaN,0.0,",,1,0700",0.0,",,1,0700",NaN,NaN,NaN,NaN,63.0,",,W",34.0,",,W",NaN,NaN,260.0,",,W",260.0,",,W",NaN,NaN,NaN,NaN,36.9,",,W",52.1,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,",,1",NaN,NaN,NaN,NaN,NaN,NaN
1864,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-01-05,10.96,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,531.0,",,W",0.0,",,W,0700",NaN,NaN,0.0,",,1,0700",0.0,",,1,0700",NaN,NaN,NaN,NaN,49.0,",,W",32.0,",,W",NaN,NaN,10.0,",,W",30.0,",,W",NaN,NaN,NaN,NaN,21.0,",,W",29.1,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315909,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2020-12-27,4.92,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,",,W,0700",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",NaN,NaN,NaN,NaN,52.0,",,W",26.0,",,W",NaN,NaN,10.0,",,W",10.0,",,W",NaN,NaN,NaN,NaN,16.1,",,W",21.0,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315910,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2020-12-28,12.53,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,",,W,0700",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",NaN,NaN,NaN,NaN,56.0,",,W",36.0,",,W",NaN,NaN,100.0,",,W",90.0,",,W",NaN,NaN,NaN,NaN,25.9,",,W",36.9,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315911,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2020-12-29,8.28,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,"T,,W,0700",NaN,NaN,0.0,"T,,W,0700",0.0,",,W,0700",NaN,NaN,NaN,NaN,46.0,",,W",27.0,",,W",NaN,NaN,330.0,",,W",340.0,",,W",NaN,NaN,NaN,NaN,19.9,",,W",25.9,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315912,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2020-12-30,6.26,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,",,W,0700",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",NaN,NaN,NaN,NaN,43.0,",,W",22.0,",,W",NaN,NaN,340.0,",,W",350.0,",,W",NaN,NaN,NaN,NaN,14.1,",,W",18.1,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315913,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2020-12-31,5.37,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,",,W,0700",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",NaN,NaN,NaN,NaN,44.0,",,W",17.0,",,W",NaN,NaN,330.0,",,W",330.0,",,W",NaN,NaN,NaN,NaN,15.0,",,W",19.0,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Cleaning

In [39]:
# assign a variable to the data from sunport so we can solely focus on that portion and begin cleaning that
sunport_w = weather_df[weather_df['STATION'] == 'USW00023050']

# Reset index so it starts cleanly from 0
sunport_w.reset_index(drop=True, inplace=True)

In [40]:
sunport_w

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,AWND,AWND_ATTRIBUTES,DAPR,DAPR_ATTRIBUTES,EVAP,EVAP_ATTRIBUTES,MDPR,MDPR_ATTRIBUTES,MNPN,MNPN_ATTRIBUTES,MXPN,MXPN_ATTRIBUTES,PGTM,PGTM_ATTRIBUTES,PRCP,PRCP_ATTRIBUTES,SN32,SN32_ATTRIBUTES,SNOW,SNOW_ATTRIBUTES,SNWD,SNWD_ATTRIBUTES,SX32,SX32_ATTRIBUTES,TAVG,TAVG_ATTRIBUTES,TMAX,TMAX_ATTRIBUTES,TMIN,TMIN_ATTRIBUTES,TOBS,TOBS_ATTRIBUTES,WDF2,WDF2_ATTRIBUTES,WDF5,WDF5_ATTRIBUTES,WESD,WESD_ATTRIBUTES,WESF,WESF_ATTRIBUTES,WSF2,WSF2_ATTRIBUTES,WSF5,WSF5_ATTRIBUTES,WT01,WT01_ATTRIBUTES,WT02,WT02_ATTRIBUTES,WT03,WT03_ATTRIBUTES,WT04,WT04_ATTRIBUTES,WT05,WT05_ATTRIBUTES,WT07,WT07_ATTRIBUTES,WT08,WT08_ATTRIBUTES,WT11,WT11_ATTRIBUTES,WT09,WT09_ATTRIBUTES,WT06,WT06_ATTRIBUTES
0,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-01-01,3.36,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,210.0,",,W",0.0,",,W,0700",NaN,NaN,0.0,",,1,0700",0.0,",,1,0700",NaN,NaN,NaN,NaN,51.0,",,W",25.0,",,W",NaN,NaN,360.0,",,W",10.0,",,W",NaN,NaN,NaN,NaN,14.1,",,W",18.1,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-01-02,3.58,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1546.0,",,W",0.0,",,W,0700",NaN,NaN,0.0,",,1,0700",0.0,",,1,0700",NaN,NaN,NaN,NaN,61.0,",,W",28.0,",,W",NaN,NaN,340.0,",,W",360.0,",,W",NaN,NaN,NaN,NaN,15.0,",,W",21.9,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-01-03,3.36,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1519.0,",,W",0.0,",,W,0700",NaN,NaN,0.0,",,1,0700",0.0,",,1,0700",NaN,NaN,NaN,NaN,57.0,",,W",30.0,",,W",NaN,NaN,110.0,",,W",190.0,",,W",NaN,NaN,NaN,NaN,10.1,",,W",12.1,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-01-04,10.51,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1530.0,",,W",0.0,",,W,0700",NaN,NaN,0.0,",,1,0700",0.0,",,1,0700",NaN,NaN,NaN,NaN,63.0,",,W",34.0,",,W",NaN,NaN,260.0,",,W",260.0,",,W",NaN,NaN,NaN,NaN,36.9,",,W",52.1,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,",,1",NaN,NaN,NaN,NaN,NaN,NaN
4,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-01-05,10.96,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,531.0,",,W",0.0,",,W,0700",NaN,NaN,0.0,",,1,0700",0.0,",,1,0700",NaN,NaN,NaN,NaN,49.0,",,W",32.0,",,W",NaN,NaN,10.0,",,W",30.0,",,W",NaN,NaN,NaN,NaN,21.0,",,W",29.1,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2020-12-27,4.92,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,",,W,0700",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",NaN,NaN,NaN,NaN,52.0,",,W",26.0,",,W",NaN,NaN,10.0,",,W",10.0,",,W",NaN,NaN,NaN,NaN,16.1,",,W",21.0,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2188,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2020-12-28,12.53,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,",,W,0700",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",NaN,NaN,NaN,NaN,56.0,",,W",36.0,",,W",NaN,NaN,100.0,",,W",90.0,",,W",NaN,NaN,NaN,NaN,25.9,",,W",36.9,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2189,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2020-12-29,8.28,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,"T,,W,0700",NaN,NaN,0.0,"T,,W,0700",0.0,",,W,0700",NaN,NaN,NaN,NaN,46.0,",,W",27.0,",,W",NaN,NaN,330.0,",,W",340.0,",,W",NaN,NaN,NaN,NaN,19.9,",,W",25.9,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2190,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2020-12-30,6.26,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,",,W,0700",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",NaN,NaN,NaN,NaN,43.0,",,W",22.0,",,W",NaN,NaN,340.0,",,W",350.0,",,W",NaN,NaN,NaN,NaN,14.1,",,W",18.1,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2191,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2020-12-31,5.37,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,",,W,0700",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",NaN,NaN,NaN,NaN,44.0,",,W",17.0,",,W",NaN,NaN,330.0,",,W",330.0,",,W",NaN,NaN,NaN,NaN,15.0,",,W",19.0,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
sunport_w.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2192 entries, 0 to 2191
Data columns (total 70 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   STATION          2192 non-null   object
 1   NAME             2192 non-null   object
 2   LATITUDE         2192 non-null   float64
 3   LONGITUDE        2192 non-null   float64
 4   ELEVATION        2192 non-null   float64
 5   DATE             2192 non-null   object
 6   AWND             2117 non-null   float64
 7   AWND_ATTRIBUTES  2117 non-null   object
 8   DAPR             0 non-null      float64
 9   DAPR_ATTRIBUTES  0 non-null      object
 10  EVAP             0 non-null      float64
 11  EVAP_ATTRIBUTES  0 non-null      object
 12  MDPR             0 non-null      float64
 13  MDPR_ATTRIBUTES  0 non-null      object
 14  MNPN             0 non-null      float64
 15  MNPN_ATTRIBUTES  0 non-null      object
 16  MXPN             0 non-null      float64
 17  MXPN_ATTRIBUTES  0 non-null      object
 18  PGTM             64 non-null     float64
 19  PGTM_ATTRIBUTES  64 non-null     object
 20  PRCP             2192 non-null   float64
 21  PRCP_ATTRIBUTES  2192 non-null   object
 22  SN32             0 non-null      float64
 23  SN32_ATTRIBUTES  0 non-null      object
 24  SNOW             2192 non-null   float64
 25  SNOW_ATTRIBUTES  2192 non-null   object
 26  SNWD             2188 non-null   float64
 27  SNWD_ATTRIBUTES  2188 non-null   object
 28  SX32             0 non-null      float64
 29  SX32_ATTRIBUTES  0 non-null      object
 30  TAVG             0 non-null      float64
 31  TAVG_ATTRIBUTES  0 non-null      float64
 32  TMAX             2192 non-null   float64
 33  TMAX_ATTRIBUTES  2192 non-null   object
 34  TMIN             2192 non-null   float64
 35  TMIN_ATTRIBUTES  2192 non-null   object
 36  TOBS             0 non-null      float64
 37  TOBS_ATTRIBUTES  0 non-null      object
 38  WDF2             2119 non-null   float64
 39  WDF2_ATTRIBUTES  2119 non-null   object
 40  WDF5             2119 non-null   float64
 41  WDF5_ATTRIBUTES  2119 non-null   object
 42  WESD             0 non-null      float64
 43  WESD_ATTRIBUTES  0 non-null      object
 44  WESF             0 non-null      float64
 45  WESF_ATTRIBUTES  0 non-null      object
 46  WSF2             2119 non-null   float64
 47  WSF2_ATTRIBUTES  2119 non-null   object
 48  WSF5             2119 non-null   float64
 49  WSF5_ATTRIBUTES  2119 non-null   object
 50  WT01             157 non-null    float64
 51  WT01_ATTRIBUTES  157 non-null    object
 52  WT02             26 non-null     float64
 53  WT02_ATTRIBUTES  26 non-null     object
 54  WT03             300 non-null    float64
 55  WT03_ATTRIBUTES  300 non-null    object
 56  WT04             0 non-null      float64
 57  WT04_ATTRIBUTES  0 non-null      object
 58  WT05             22 non-null     float64
 59  WT05_ATTRIBUTES  22 non-null     object
 60  WT07             22 non-null     float64
 61  WT07_ATTRIBUTES  22 non-null     object
 62  WT08             187 non-null    float64
 63  WT08_ATTRIBUTES  187 non-null    object
 64  WT11             0 non-null      float64
 65  WT11_ATTRIBUTES  0 non-null      object
 66  WT09             7 non-null      float64
 67  WT09_ATTRIBUTES  7 non-null      object
 68  WT06             2 non-null      float64
 69  WT06_ATTRIBUTES  2 non-null      object
dtypes: float64(36), object(34)
memory usage: 1.2+ MB

In [42]:
# this data has a lot of nulls will beging by fuguring out what columns are 100% nulls if any then drop.
sunport_w = sunport_w.dropna(axis=1, how='all')

In [43]:
# lowered our data from 70 columns to 44
# still have columns that only have very few values I will be dropping those too
sunport_w.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2192 entries, 0 to 2191
Data columns (total 44 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   STATION          2192 non-null   object
 1   NAME             2192 non-null   object
 2   LATITUDE         2192 non-null   float64
 3   LONGITUDE        2192 non-null   float64
 4   ELEVATION        2192 non-null   float64
 5   DATE             2192 non-null   object
 6   AWND             2117 non-null   float64
 7   AWND_ATTRIBUTES  2117 non-null   object
 8   PGTM             64 non-null     float64
 9   PGTM_ATTRIBUTES  64 non-null     object
 10  PRCP             2192 non-null   float64
 11  PRCP_ATTRIBUTES  2192 non-null   object
 12  SNOW             2192 non-null   float64
 13  SNOW_ATTRIBUTES  2192 non-null   object
 14  SNWD             2188 non-null   float64
 15  SNWD_ATTRIBUTES  2188 non-null   object
 16  TMAX             2192 non-null   float64
 17  TMAX_ATTRIBUTES  2192 non-null   object
 18  TMIN             2192 non-null   float64
 19  TMIN_ATTRIBUTES  2192 non-null   object
 20  WDF2             2119 non-null   float64
 21  WDF2_ATTRIBUTES  2119 non-null   object
 22  WDF5             2119 non-null   float64
 23  WDF5_ATTRIBUTES  2119 non-null   object
 24  WSF2             2119 non-null   float64
 25  WSF2_ATTRIBUTES  2119 non-null   object
 26  WSF5             2119 non-null   float64
 27  WSF5_ATTRIBUTES  2119 non-null   object
 28  WT01             157 non-null    float64
 29  WT01_ATTRIBUTES  157 non-null    object
 30  WT02             26 non-null     float64
 31  WT02_ATTRIBUTES  26 non-null     object
 32  WT03             300 non-null    float64
 33  WT03_ATTRIBUTES  300 non-null    object
 34  WT05             22 non-null     float64
 35  WT05_ATTRIBUTES  22 non-null     object
 36  WT07             22 non-null     float64
 37  WT07_ATTRIBUTES  22 non-null     object
 38  WT08             187 non-null    float64
 39  WT08_ATTRIBUTES  187 non-null    object
 40  WT09             7 non-null      float64
 41  WT09_ATTRIBUTES  7 non-null      object
 42  WT06             2 non-null      float64
 43  WT06_ATTRIBUTES  2 non-null      object
dtypes: float64(22), object(22)
memory usage: 753.6+ KB

In [44]:
sunport_w

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,AWND,AWND_ATTRIBUTES,PGTM,PGTM_ATTRIBUTES,PRCP,PRCP_ATTRIBUTES,SNOW,SNOW_ATTRIBUTES,SNWD,SNWD_ATTRIBUTES,TMAX,TMAX_ATTRIBUTES,TMIN,TMIN_ATTRIBUTES,WDF2,WDF2_ATTRIBUTES,WDF5,WDF5_ATTRIBUTES,WSF2,WSF2_ATTRIBUTES,WSF5,WSF5_ATTRIBUTES,WT01,WT01_ATTRIBUTES,WT02,WT02_ATTRIBUTES,WT03,WT03_ATTRIBUTES,WT05,WT05_ATTRIBUTES,WT07,WT07_ATTRIBUTES,WT08,WT08_ATTRIBUTES,WT09,WT09_ATTRIBUTES,WT06,WT06_ATTRIBUTES
0,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-01-01,3.36,",,W",210.0,",,W",0.0,",,W,0700",0.0,",,1,0700",0.0,",,1,0700",51.0,",,W",25.0,",,W",360.0,",,W",10.0,",,W",14.1,",,W",18.1,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-01-02,3.58,",,W",1546.0,",,W",0.0,",,W,0700",0.0,",,1,0700",0.0,",,1,0700",61.0,",,W",28.0,",,W",340.0,",,W",360.0,",,W",15.0,",,W",21.9,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-01-03,3.36,",,W",1519.0,",,W",0.0,",,W,0700",0.0,",,1,0700",0.0,",,1,0700",57.0,",,W",30.0,",,W",110.0,",,W",190.0,",,W",10.1,",,W",12.1,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-01-04,10.51,",,W",1530.0,",,W",0.0,",,W,0700",0.0,",,1,0700",0.0,",,1,0700",63.0,",,W",34.0,",,W",260.0,",,W",260.0,",,W",36.9,",,W",52.1,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,",,1",NaN,NaN,NaN,NaN
4,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-01-05,10.96,",,W",531.0,",,W",0.0,",,W,0700",0.0,",,1,0700",0.0,",,1,0700",49.0,",,W",32.0,",,W",10.0,",,W",30.0,",,W",21.0,",,W",29.1,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2020-12-27,4.92,",,W",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",0.0,",,W,0700",52.0,",,W",26.0,",,W",10.0,",,W",10.0,",,W",16.1,",,W",21.0,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2188,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2020-12-28,12.53,",,W",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",0.0,",,W,0700",56.0,",,W",36.0,",,W",100.0,",,W",90.0,",,W",25.9,",,W",36.9,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2189,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2020-12-29,8.28,",,W",NaN,NaN,0.0,"T,,W,0700",0.0,"T,,W,0700",0.0,",,W,0700",46.0,",,W",27.0,",,W",330.0,",,W",340.0,",,W",19.9,",,W",25.9,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2190,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2020-12-30,6.26,",,W",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",0.0,",,W,0700",43.0,",,W",22.0,",,W",340.0,",,W",350.0,",,W",14.1,",,W",18.1,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2191,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2020-12-31,5.37,",,W",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",0.0,",,W,0700",44.0,",,W",17.0,",,W",330.0,",,W",330.0,",,W",15.0,",,W",19.0,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
# not only am I dropping the following values because they have high nulls. not sure if I should its RARE weather
#sunport_w.drop( columns = ['WT07','WT05', 'WT05_ATTRIBUTES','WT07','WT07_ATTRIBUTES','WT01','WT01_ATTRIBUTES','WT08','WT08_ATTRIBUTES','WT03', 'WT03_ATTRIBUTES'])

parquet

In [46]:
parquet_file = "sunport_w.parquet"
parquet_file

'sunport_w.parquet'

In [47]:
sunport_w.to_parquet( parquet_file, index=False)

In [48]:
!ls -l --si {parquet_file}

-rw-r--r-- 1 root root 56k Jul 28 16:50 sunport_w.parquet

In [49]:
df2 = pd.read_parquet( parquet_file )
df2.shape

(2192, 44)

Hugging Face

In [50]:
os.environ['HF_TOKEN'] = userdata.get('hf_cs_token')
_ = os.environ["HF_TOKEN"]
f"{_[:5]} ... {_[-3:]}"

'hf_wi ... azj'

In [51]:
os.environ["HF_ACCOUNT"] = userdata.get('hf_account')
hf_account = os.environ["HF_ACCOUNT"]
hf_account

'zenithvalor'

In [52]:
hf_org = "ddds-Capstone"
os.environ["HF_ORG"] = hf_org
hf_org

'ddds-Capstone'

In [53]:
hf_repo = "Datasets"
os.environ["HF_REPO"] = hf_repo
hf_repo

'Datasets'

In [54]:
!hf auth login --token $HF_TOKEN

Hint: A new version of huggingface_hub (1.25.1) is available! You are using version 1.23.0.
To update, run: hf update
The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `hf`CLI if you want to set the git credential as well.
Token is valid (permission: fineGrained).
The token `Juan_R_token` has been saved to /root/.cache/huggingface/stored_tokens
Your token has been saved to /root/.cache/huggingface/token
Login successful.
Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

push to hugging face

In [55]:
%%writefile test.txt
hello

Writing test.txt

In [56]:
!ls -l

total 63160
-rw-r--r-- 1 root root 10526903 Jul 28 16:35 '2025 abq weather.csv'
drwx------ 5 root root     4096 Jul 28 16:35  drive
drwxr-xr-x 1 root root     4096 Jun  4 13:32  sample_data
-rw-r--r-- 1 root root    55410 Jul 28 16:50  sunport_w.parquet
-rw-r--r-- 1 root root        6 Jul 28 16:51  test.txt
-rw-r--r-- 1 root root 10114467 Jul 28 16:35 'weather 2020.csv'
-rw-r--r-- 1 root root 22074110 Jul 28 16:35 'weather 2021-2022.csv'
-rw-r--r-- 1 root root 21879907 Jul 28 16:35 'weather 2023-2024.csv'

In [57]:
%%capture hf_upload
%%bash
hf upload \
  --type dataset \
  ${HF_ORG}/${HF_REPO} \
  sunport_w.parquet

In [58]:
print(hf_upload.stdout)

✓ Uploaded
  url: https://huggingface.co/datasets/ddds-Capstone/Datasets/commit/6b721385f5a2e5e69cc40cb94f6b85857eed318f

In [59]:
hf_url = f"https://huggingface.co/datasets/{hf_org}/{hf_repo}/resolve/main/sunport_w.parquet"
hf_url

'https://huggingface.co/datasets/ddds-Capstone/Datasets/resolve/main/sunport_w.parquet'

In [60]:
df3 = pd.read_parquet( hf_url )
df3.shape

(2192, 44)

In [61]:
df3.iloc[:,:5].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2192 entries, 0 to 2191
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   STATION    2192 non-null   object
 1   NAME       2192 non-null   object
 2   LATITUDE   2192 non-null   float64
 3   LONGITUDE  2192 non-null   float64
 4   ELEVATION  2192 non-null   float64
dtypes: float64(3), object(2)
memory usage: 85.8+ KB