<a href="https://colab.research.google.com/github/JuanReyesAn/Data-Science-Portfolio-C21/blob/main/ABQ_Weather_2020_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import glob
import os

from google.colab import userdata, files, drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# 4 urls each with the same kind of data just different years. i will be concatinating them

In [ ]:
url1 = '/content/2025 abq weather.csv'
url2 = '/content/weather 2023-2024.csv'
url3 = '/content/weather 2021-2022.csv'
url4 = '/content/weather 2020.csv'

In [7]:
folder_path = '/content/drive/MyDrive/ddds-cohort-21/Projects/Capstone/ABQ Sunport Weather'

#Use glob to find all files ending in .csv inside folder
csv_files = glob.glob(os.path.join(folder_path, "*.csv"))

#Read each CSV into a list of DataFrames
df_list = []
for file in csv_files:
    # Read the current CSV file
    df = pd.read_csv(file)
    df_list.append(df)

#Combine all individual DataFrames into one large DataFrame
weather_df = pd.concat(df_list, ignore_index=True)
weather_df.head()

NameError: name 'glob' is not defined

In [8]:
weather_df.info()

NameError: name 'weather_df' is not defined

In [ ]:
weather_df.columns.tolist()

['STATION',
 'NAME',
 'LATITUDE',
 'LONGITUDE',
 'ELEVATION',
 'DATE',
 'AWND',
 'AWND_ATTRIBUTES',
 'DAPR',
 'DAPR_ATTRIBUTES',
 'EVAP',
 'EVAP_ATTRIBUTES',
 'MDPR',
 'MDPR_ATTRIBUTES',
 'MNPN',
 'MNPN_ATTRIBUTES',
 'MXPN',
 'MXPN_ATTRIBUTES',
 'PGTM',
 'PGTM_ATTRIBUTES',
 'PRCP',
 'PRCP_ATTRIBUTES',
 'SN32',
 'SN32_ATTRIBUTES',
 'SNOW',
 'SNOW_ATTRIBUTES',
 'SNWD',
 'SNWD_ATTRIBUTES',
 'SX32',
 'SX32_ATTRIBUTES',
 'TAVG',
 'TAVG_ATTRIBUTES',
 'TMAX',
 'TMAX_ATTRIBUTES',
 'TMIN',
 'TMIN_ATTRIBUTES',
 'TOBS',
 'TOBS_ATTRIBUTES',
 'WDF2',
 'WDF2_ATTRIBUTES',
 'WDF5',
 'WDF5_ATTRIBUTES',
 'WESD',
 'WESD_ATTRIBUTES',
 'WESF',
 'WESF_ATTRIBUTES',
 'WSF2',
 'WSF2_ATTRIBUTES',
 'WSF5',
 'WSF5_ATTRIBUTES',
 'WT01',
 'WT01_ATTRIBUTES',
 'WT02',
 'WT02_ATTRIBUTES',
 'WT03',
 'WT03_ATTRIBUTES',
 'WT04',
 'WT04_ATTRIBUTES',
 'WT05',
 'WT05_ATTRIBUTES',
 'WT07',
 'WT07_ATTRIBUTES',
 'WT08',
 'WT08_ATTRIBUTES',
 'WT09',
 'WT09_ATTRIBUTES',
 'WT11',
 'WT11_ATTRIBUTES',
 'WT06',
 'WT06_ATTRIBUTES']

In [ ]:
# we got a lot of nulls and stattions that we do not need for now
pd.set_option('display.max_columns', None)

# Display the first 5 rows with every column visible
weather_df.head(5)

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,AWND,AWND_ATTRIBUTES,DAPR,DAPR_ATTRIBUTES,EVAP,EVAP_ATTRIBUTES,MDPR,MDPR_ATTRIBUTES,MNPN,MNPN_ATTRIBUTES,MXPN,MXPN_ATTRIBUTES,PGTM,PGTM_ATTRIBUTES,PRCP,PRCP_ATTRIBUTES,SN32,SN32_ATTRIBUTES,SNOW,SNOW_ATTRIBUTES,SNWD,SNWD_ATTRIBUTES,SX32,SX32_ATTRIBUTES,TAVG,TAVG_ATTRIBUTES,TMAX,TMAX_ATTRIBUTES,TMIN,TMIN_ATTRIBUTES,TOBS,TOBS_ATTRIBUTES,WDF2,WDF2_ATTRIBUTES,WDF5,WDF5_ATTRIBUTES,WESD,WESD_ATTRIBUTES,WESF,WESF_ATTRIBUTES,WSF2,WSF2_ATTRIBUTES,WSF5,WSF5_ATTRIBUTES,WT01,WT01_ATTRIBUTES,WT02,WT02_ATTRIBUTES,WT03,WT03_ATTRIBUTES,WT04,WT04_ATTRIBUTES,WT05,WT05_ATTRIBUTES,WT07,WT07_ATTRIBUTES,WT08,WT08_ATTRIBUTES,WT09,WT09_ATTRIBUTES,WT11,WT11_ATTRIBUTES,WT06,WT06_ATTRIBUTES
0,US1NMSF0052,"EDGEWOOD 2.1 WNW, NM US",35.090167,-106.211958,2013.8,2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,",,N",NaN,NaN,0.0,",,N",0.0,",,N",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,US1NMSF0052,"EDGEWOOD 2.1 WNW, NM US",35.090167,-106.211958,2013.8,2021-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,",,N",NaN,NaN,0.0,",,N",0.0,",,N",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,US1NMSF0052,"EDGEWOOD 2.1 WNW, NM US",35.090167,-106.211958,2013.8,2021-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,",,N",NaN,NaN,0.0,",,N",0.0,",,N",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,US1NMSF0052,"EDGEWOOD 2.1 WNW, NM US",35.090167,-106.211958,2013.8,2021-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,",,N",NaN,NaN,0.0,",,N",0.0,",,N",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,US1NMSF0052,"EDGEWOOD 2.1 WNW, NM US",35.090167,-106.211958,2013.8,2021-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,",,N",NaN,NaN,0.0,",,N",0.0,",,N",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# looking for sunport station
weather_df[['STATION', 'NAME']].value_counts()

STATION      NAME
USW00023050  ALBUQUERQUE INTERNATIONAL AIRPORT, NM US    2192
USC00297481  RIO RANCHO NUMBER 2, NM US                  2192
USC00297477  RIO RANCHO NUMBER 1, NM US                  2192
US1NMVL0037  PERALTA 0.6 S, NM US                        2192
US1NMBR0139  ALBUQUERQUE 3.5 NNE, NM US                  2192
                                                         ...
US1NMBR0479  ALBUQUERQUE 4.0 SSE, NM US                    15
US1NMBR0196  ALBUQUERQUE 6.2 E, NM US                      11
US1NMBR0011  ALBUQUERQUE 8 ENE, NM US                       2
US1NMSN0047  CORRALES 1.6 SSW, NM US                        1
US1NMVL0035  LOS LUNAS 4.6 SE, NM US                        1
Name: count, Length: 316, dtype: int64

In [ ]:
# specifically looking at the temperature in sunport/Albuquerque, NM
filter = (weather_df['STATION'] == 'USW00023050')
weather_df[filter]

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,AWND,AWND_ATTRIBUTES,DAPR,DAPR_ATTRIBUTES,EVAP,EVAP_ATTRIBUTES,MDPR,MDPR_ATTRIBUTES,MNPN,MNPN_ATTRIBUTES,MXPN,MXPN_ATTRIBUTES,PGTM,PGTM_ATTRIBUTES,PRCP,PRCP_ATTRIBUTES,SN32,SN32_ATTRIBUTES,SNOW,SNOW_ATTRIBUTES,SNWD,SNWD_ATTRIBUTES,SX32,SX32_ATTRIBUTES,TAVG,TAVG_ATTRIBUTES,TMAX,TMAX_ATTRIBUTES,TMIN,TMIN_ATTRIBUTES,TOBS,TOBS_ATTRIBUTES,WDF2,WDF2_ATTRIBUTES,WDF5,WDF5_ATTRIBUTES,WESD,WESD_ATTRIBUTES,WESF,WESF_ATTRIBUTES,WSF2,WSF2_ATTRIBUTES,WSF5,WSF5_ATTRIBUTES,WT01,WT01_ATTRIBUTES,WT02,WT02_ATTRIBUTES,WT03,WT03_ATTRIBUTES,WT04,WT04_ATTRIBUTES,WT05,WT05_ATTRIBUTES,WT07,WT07_ATTRIBUTES,WT08,WT08_ATTRIBUTES,WT09,WT09_ATTRIBUTES,WT11,WT11_ATTRIBUTES,WT06,WT06_ATTRIBUTES
5593,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2021-01-01,5.59,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,",,W,0700",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",NaN,NaN,NaN,NaN,45.0,",,W",20.0,",,W",NaN,NaN,10.0,",,W",20.0,",,W",NaN,NaN,NaN,NaN,17.0,",,W",19.9,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5594,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2021-01-02,6.49,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,",,W,0700",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",NaN,NaN,NaN,NaN,46.0,",,W",19.0,",,W",NaN,NaN,350.0,",,W",350.0,",,W",NaN,NaN,NaN,NaN,16.1,",,W",23.9,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5595,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2021-01-03,6.26,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,",,W,0700",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",NaN,NaN,NaN,NaN,49.0,",,W",26.0,",,W",NaN,NaN,360.0,",,W",340.0,",,W",NaN,NaN,NaN,NaN,17.0,",,W",25.1,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5596,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2021-01-04,4.47,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,",,W,0700",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",NaN,NaN,NaN,NaN,51.0,",,W",27.0,",,W",NaN,NaN,350.0,",,W",340.0,",,W",NaN,NaN,NaN,NaN,16.1,",,W",23.9,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5597,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2021-01-05,9.17,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,",,W,0700",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",NaN,NaN,NaN,NaN,57.0,",,W",26.0,",,W",NaN,NaN,330.0,",,W",330.0,",,W",NaN,NaN,NaN,NaN,25.1,",,W",36.9,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310917,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.07,",,1,0700",NaN,NaN,0.0,",,1,0700",0.0,",,1,0700",NaN,NaN,NaN,NaN,53.0,",,1",46.0,",,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310918,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,",,1,0700",NaN,NaN,0.0,",,1,0700",0.0,",,1,0700",NaN,NaN,NaN,NaN,48.0,",,1",36.0,",,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310919,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,",,1,0700",NaN,NaN,0.0,",,1,0700",0.0,",,1,0700",NaN,NaN,NaN,NaN,49.0,",,1",29.0,",,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310920,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-12-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,",,1,0700",NaN,NaN,0.0,",,1,0700",0.0,",,1,0700",NaN,NaN,NaN,NaN,51.0,",,1",25.0,",,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310921,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,",,1,0700",NaN,NaN,0.0,",,1,0700",0.0,",,1,0700",NaN,NaN,NaN,NaN,57.0,",,1",30.0,",,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Cleaning

In [ ]:
# assign a variable to the data from sunport so we can solely focus on that portion and begin cleaning that
sunport_w = weather_df[weather_df['STATION'] == 'USW00023050']

# Reset index so it starts cleanly from 0
sunport_w.reset_index(drop=True, inplace=True)

In [ ]:
sunport_w

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,AWND,AWND_ATTRIBUTES,DAPR,DAPR_ATTRIBUTES,EVAP,EVAP_ATTRIBUTES,MDPR,MDPR_ATTRIBUTES,MNPN,MNPN_ATTRIBUTES,MXPN,MXPN_ATTRIBUTES,PGTM,PGTM_ATTRIBUTES,PRCP,PRCP_ATTRIBUTES,SN32,SN32_ATTRIBUTES,SNOW,SNOW_ATTRIBUTES,SNWD,SNWD_ATTRIBUTES,SX32,SX32_ATTRIBUTES,TAVG,TAVG_ATTRIBUTES,TMAX,TMAX_ATTRIBUTES,TMIN,TMIN_ATTRIBUTES,TOBS,TOBS_ATTRIBUTES,WDF2,WDF2_ATTRIBUTES,WDF5,WDF5_ATTRIBUTES,WESD,WESD_ATTRIBUTES,WESF,WESF_ATTRIBUTES,WSF2,WSF2_ATTRIBUTES,WSF5,WSF5_ATTRIBUTES,WT01,WT01_ATTRIBUTES,WT02,WT02_ATTRIBUTES,WT03,WT03_ATTRIBUTES,WT04,WT04_ATTRIBUTES,WT05,WT05_ATTRIBUTES,WT07,WT07_ATTRIBUTES,WT08,WT08_ATTRIBUTES,WT09,WT09_ATTRIBUTES,WT11,WT11_ATTRIBUTES,WT06,WT06_ATTRIBUTES
0,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2021-01-01,5.59,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,",,W,0700",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",NaN,NaN,NaN,NaN,45.0,",,W",20.0,",,W",NaN,NaN,10.0,",,W",20.0,",,W",NaN,NaN,NaN,NaN,17.0,",,W",19.9,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2021-01-02,6.49,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,",,W,0700",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",NaN,NaN,NaN,NaN,46.0,",,W",19.0,",,W",NaN,NaN,350.0,",,W",350.0,",,W",NaN,NaN,NaN,NaN,16.1,",,W",23.9,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2021-01-03,6.26,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,",,W,0700",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",NaN,NaN,NaN,NaN,49.0,",,W",26.0,",,W",NaN,NaN,360.0,",,W",340.0,",,W",NaN,NaN,NaN,NaN,17.0,",,W",25.1,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2021-01-04,4.47,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,",,W,0700",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",NaN,NaN,NaN,NaN,51.0,",,W",27.0,",,W",NaN,NaN,350.0,",,W",340.0,",,W",NaN,NaN,NaN,NaN,16.1,",,W",23.9,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2021-01-05,9.17,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,",,W,0700",NaN,NaN,0.0,",,W,0700",0.0,",,W,0700",NaN,NaN,NaN,NaN,57.0,",,W",26.0,",,W",NaN,NaN,330.0,",,W",330.0,",,W",NaN,NaN,NaN,NaN,25.1,",,W",36.9,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.07,",,1,0700",NaN,NaN,0.0,",,1,0700",0.0,",,1,0700",NaN,NaN,NaN,NaN,53.0,",,1",46.0,",,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2188,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,",,1,0700",NaN,NaN,0.0,",,1,0700",0.0,",,1,0700",NaN,NaN,NaN,NaN,48.0,",,1",36.0,",,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2189,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,",,1,0700",NaN,NaN,0.0,",,1,0700",0.0,",,1,0700",NaN,NaN,NaN,NaN,49.0,",,1",29.0,",,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2190,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-12-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,",,1,0700",NaN,NaN,0.0,",,1,0700",0.0,",,1,0700",NaN,NaN,NaN,NaN,51.0,",,1",25.0,",,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2191,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,",,1,0700",NaN,NaN,0.0,",,1,0700",0.0,",,1,0700",NaN,NaN,NaN,NaN,57.0,",,1",30.0,",,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
sunport_w.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2192 entries, 0 to 2191
Data columns (total 70 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   STATION          2192 non-null   object
 1   NAME             2192 non-null   object
 2   LATITUDE         2192 non-null   float64
 3   LONGITUDE        2192 non-null   float64
 4   ELEVATION        2192 non-null   float64
 5   DATE             2192 non-null   object
 6   AWND             2117 non-null   float64
 7   AWND_ATTRIBUTES  2117 non-null   object
 8   DAPR             0 non-null      float64
 9   DAPR_ATTRIBUTES  0 non-null      object
 10  EVAP             0 non-null      float64
 11  EVAP_ATTRIBUTES  0 non-null      object
 12  MDPR             0 non-null      float64
 13  MDPR_ATTRIBUTES  0 non-null      object
 14  MNPN             0 non-null      float64
 15  MNPN_ATTRIBUTES  0 non-null      object
 16  MXPN             0 non-null      float64
 17  MXPN_ATTRIBUTES  0 non-null      object
 18  PGTM             64 non-null     float64
 19  PGTM_ATTRIBUTES  64 non-null     object
 20  PRCP             2192 non-null   float64
 21  PRCP_ATTRIBUTES  2192 non-null   object
 22  SN32             0 non-null      float64
 23  SN32_ATTRIBUTES  0 non-null      object
 24  SNOW             2192 non-null   float64
 25  SNOW_ATTRIBUTES  2192 non-null   object
 26  SNWD             2188 non-null   float64
 27  SNWD_ATTRIBUTES  2188 non-null   object
 28  SX32             0 non-null      float64
 29  SX32_ATTRIBUTES  0 non-null      object
 30  TAVG             0 non-null      float64
 31  TAVG_ATTRIBUTES  0 non-null      float64
 32  TMAX             2192 non-null   float64
 33  TMAX_ATTRIBUTES  2192 non-null   object
 34  TMIN             2192 non-null   float64
 35  TMIN_ATTRIBUTES  2192 non-null   object
 36  TOBS             0 non-null      float64
 37  TOBS_ATTRIBUTES  0 non-null      object
 38  WDF2             2119 non-null   float64
 39  WDF2_ATTRIBUTES  2119 non-null   object
 40  WDF5             2119 non-null   float64
 41  WDF5_ATTRIBUTES  2119 non-null   object
 42  WESD             0 non-null      float64
 43  WESD_ATTRIBUTES  0 non-null      object
 44  WESF             0 non-null      float64
 45  WESF_ATTRIBUTES  0 non-null      object
 46  WSF2             2119 non-null   float64
 47  WSF2_ATTRIBUTES  2119 non-null   object
 48  WSF5             2119 non-null   float64
 49  WSF5_ATTRIBUTES  2119 non-null   object
 50  WT01             157 non-null    float64
 51  WT01_ATTRIBUTES  157 non-null    object
 52  WT02             26 non-null     float64
 53  WT02_ATTRIBUTES  26 non-null     object
 54  WT03             300 non-null    float64
 55  WT03_ATTRIBUTES  300 non-null    object
 56  WT04             0 non-null      float64
 57  WT04_ATTRIBUTES  0 non-null      object
 58  WT05             22 non-null     float64
 59  WT05_ATTRIBUTES  22 non-null     object
 60  WT07             22 non-null     float64
 61  WT07_ATTRIBUTES  22 non-null     object
 62  WT08             187 non-null    float64
 63  WT08_ATTRIBUTES  187 non-null    object
 64  WT09             7 non-null      float64
 65  WT09_ATTRIBUTES  7 non-null      object
 66  WT11             0 non-null      float64
 67  WT11_ATTRIBUTES  0 non-null      object
 68  WT06             2 non-null      float64
 69  WT06_ATTRIBUTES  2 non-null      object
dtypes: float64(36), object(34)
memory usage: 1.2+ MB

In [ ]:
# this data has a lot of nulls will beging by fuguring out what columns are 100% nulls if any then drop.
sunport_w = sunport_w.dropna(axis=1, how='all')

In [ ]:
# lowered our data from 70 columns to 44
# still have columns that only have very few values I will be dropping those too
sunport_w.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2192 entries, 0 to 2191
Data columns (total 44 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   STATION          2192 non-null   object
 1   NAME             2192 non-null   object
 2   LATITUDE         2192 non-null   float64
 3   LONGITUDE        2192 non-null   float64
 4   ELEVATION        2192 non-null   float64
 5   DATE             2192 non-null   object
 6   AWND             2117 non-null   float64
 7   AWND_ATTRIBUTES  2117 non-null   object
 8   PGTM             64 non-null     float64
 9   PGTM_ATTRIBUTES  64 non-null     object
 10  PRCP             2192 non-null   float64
 11  PRCP_ATTRIBUTES  2192 non-null   object
 12  SNOW             2192 non-null   float64
 13  SNOW_ATTRIBUTES  2192 non-null   object
 14  SNWD             2188 non-null   float64
 15  SNWD_ATTRIBUTES  2188 non-null   object
 16  TMAX             2192 non-null   float64
 17  TMAX_ATTRIBUTES  2192 non-null   object
 18  TMIN             2192 non-null   float64
 19  TMIN_ATTRIBUTES  2192 non-null   object
 20  WDF2             2119 non-null   float64
 21  WDF2_ATTRIBUTES  2119 non-null   object
 22  WDF5             2119 non-null   float64
 23  WDF5_ATTRIBUTES  2119 non-null   object
 24  WSF2             2119 non-null   float64
 25  WSF2_ATTRIBUTES  2119 non-null   object
 26  WSF5             2119 non-null   float64
 27  WSF5_ATTRIBUTES  2119 non-null   object
 28  WT01             157 non-null    float64
 29  WT01_ATTRIBUTES  157 non-null    object
 30  WT02             26 non-null     float64
 31  WT02_ATTRIBUTES  26 non-null     object
 32  WT03             300 non-null    float64
 33  WT03_ATTRIBUTES  300 non-null    object
 34  WT05             22 non-null     float64
 35  WT05_ATTRIBUTES  22 non-null     object
 36  WT07             22 non-null     float64
 37  WT07_ATTRIBUTES  22 non-null     object
 38  WT08             187 non-null    float64
 39  WT08_ATTRIBUTES  187 non-null    object
 40  WT09             7 non-null      float64
 41  WT09_ATTRIBUTES  7 non-null      object
 42  WT06             2 non-null      float64
 43  WT06_ATTRIBUTES  2 non-null      object
dtypes: float64(22), object(22)
memory usage: 753.6+ KB

In [ ]:
sunport_w

,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,AWND,AWND_ATTRIBUTES,PGTM,PGTM_ATTRIBUTES,PRCP,PRCP_ATTRIBUTES,SNOW,SNOW_ATTRIBUTES,SNWD,SNWD_ATTRIBUTES,TMAX,TMAX_ATTRIBUTES,TMIN,TMIN_ATTRIBUTES,WDF2,WDF2_ATTRIBUTES,WDF5,WDF5_ATTRIBUTES,WSF2,WSF2_ATTRIBUTES,WSF5,WSF5_ATTRIBUTES,WT01,WT01_ATTRIBUTES,WT02,WT02_ATTRIBUTES,WT03,WT03_ATTRIBUTES,WT05,WT05_ATTRIBUTES,WT07,WT07_ATTRIBUTES,WT08,WT08_ATTRIBUTES,WT09,WT09_ATTRIBUTES,WT06,WT06_ATTRIBUTES
0,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2021-01-01,5.59,",,W",NaN,NaN,0.00,",,W,0700",0.0,",,W,0700",0.0,",,W,0700",45.0,",,W",20.0,",,W",10.0,",,W",20.0,",,W",17.0,",,W",19.9,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2021-01-02,6.49,",,W",NaN,NaN,0.00,",,W,0700",0.0,",,W,0700",0.0,",,W,0700",46.0,",,W",19.0,",,W",350.0,",,W",350.0,",,W",16.1,",,W",23.9,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2021-01-03,6.26,",,W",NaN,NaN,0.00,",,W,0700",0.0,",,W,0700",0.0,",,W,0700",49.0,",,W",26.0,",,W",360.0,",,W",340.0,",,W",17.0,",,W",25.1,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2021-01-04,4.47,",,W",NaN,NaN,0.00,",,W,0700",0.0,",,W,0700",0.0,",,W,0700",51.0,",,W",27.0,",,W",350.0,",,W",340.0,",,W",16.1,",,W",23.9,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2021-01-05,9.17,",,W",NaN,NaN,0.00,",,W,0700",0.0,",,W,0700",0.0,",,W,0700",57.0,",,W",26.0,",,W",330.0,",,W",330.0,",,W",25.1,",,W",36.9,",,W",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-12-27,NaN,NaN,NaN,NaN,0.07,",,1,0700",0.0,",,1,0700",0.0,",,1,0700",53.0,",,1",46.0,",,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2188,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-12-28,NaN,NaN,NaN,NaN,0.00,",,1,0700",0.0,",,1,0700",0.0,",,1,0700",48.0,",,1",36.0,",,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2189,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-12-29,NaN,NaN,NaN,NaN,0.00,",,1,0700",0.0,",,1,0700",0.0,",,1,0700",49.0,",,1",29.0,",,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2190,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-12-30,NaN,NaN,NaN,NaN,0.00,",,1,0700",0.0,",,1,0700",0.0,",,1,0700",51.0,",,1",25.0,",,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2191,USW00023050,"ALBUQUERQUE INTERNATIONAL AIRPORT, NM US",35.04189,-106.61545,1618.4,2025-12-31,NaN,NaN,NaN,NaN,0.00,",,1,0700",0.0,",,1,0700",0.0,",,1,0700",57.0,",,1",30.0,",,1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# not only am I dropping the following values because they have high nulls. not sure if I should its RARE weather
#sunport_w.drop( columns = ['WT07','WT05', 'WT05_ATTRIBUTES','WT07','WT07_ATTRIBUTES','WT01','WT01_ATTRIBUTES','WT08','WT08_ATTRIBUTES','WT03', 'WT03_ATTRIBUTES'])

parquet

In [ ]:
parquet_file = "sunport_w.parquet"
parquet_file

'sunport_w.parquet'

In [ ]:
sunport_w.to_parquet( parquet_file, index=False)

In [ ]:
!ls -l --si {parquet_file}

-rw-r--r-- 1 root root 56k Jul 28 16:30 sunport_w.parquet

In [ ]:
df2 = pd.read_parquet( parquet_file )
df2.shape

(2192, 44)

Hugging Face

In [ ]:
os.environ['HF_TOKEN'] = userdata.get('hf_cs_token')
_ = os.environ["HF_TOKEN"]
f"{_[:5]} ... {_[-3:]}"

'hf_ld ... iLe'

In [ ]:
os.environ["HF_ACCOUNT"] = userdata.get('hf_account')
hf_account = os.environ["HF_ACCOUNT"]
hf_account

'stephanie465337'

In [ ]:
hf_org = "ddds-Capstone"
os.environ["HF_ORG"] = hf_org
hf_org

'ddds-Capstone'

In [ ]:
hf_repo = "Datasets"
os.environ["HF_REPO"] = hf_repo
hf_repo

'Datasets'

In [ ]:
!hf auth login --token $HF_TOKEN

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `hf`CLI if you want to set the git credential as well.
Token is valid (permission: fineGrained).
The token `Capstone Token` has been saved to /root/.cache/huggingface/stored_tokens
Your token has been saved to /root/.cache/huggingface/token
Login successful.
Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

push to hugging face

In [ ]:
%%writefile test.txt
hello

Overwriting test.txt

In [ ]:
!ls -l

total 740
drwx------ 5 root root   4096 Jul 28 16:18 drive
drwxr-xr-x 1 root root   4096 Jun  4 13:32 sample_data
-rw-r--r-- 1 root root  55308 Jul 28 16:30 sunport_w.parquet
-rw-r--r-- 1 root root      6 Jul 28 16:30 test.txt
-rw-r--r-- 1 root root 684717 Jul 28 16:23 weather.parquet

In [ ]:
%%capture hf_upload
%%bash
hf upload \
  --type dataset \
  ${HF_ORG}/${HF_REPO} \
  sunport_w.parquet

In [ ]:
print(hf_upload.stdout)

✓ Uploaded
  url: https://huggingface.co/datasets/ddds-Capstone/Datasets/commit/ce7c6a5d9f8d93b623d0efeab328af84ecbfad11

In [ ]:
hf_url = f"https://huggingface.co/datasets/{hf_org}/{hf_repo}/resolve/main/sunport_w.parquet"
hf_url

'https://huggingface.co/datasets/ddds-Capstone/Datasets/resolve/main/sunport_w.parquet'

In [ ]:
df3 = pd.read_parquet( hf_url )
df3.shape

(2192, 44)

In [ ]:
df3.iloc[:,:5].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2192 entries, 0 to 2191
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   STATION    2192 non-null   object
 1   NAME       2192 non-null   object
 2   LATITUDE   2192 non-null   float64
 3   LONGITUDE  2192 non-null   float64
 4   ELEVATION  2192 non-null   float64
dtypes: float64(3), object(2)
memory usage: 85.8+ KB