# Project SQL - BigQuery

## Pick a dataset that interests you (or multiple data sets)

Use the Open Data Sets available from Google BigQuery. You can use your own Google account or Kaggle.

## Come up with questions about your data
* What sort of information is in this dataset?
* How many records are there?
* Have the number of bitcoin transactions increased year over year?
* Does New Mexico get more or less rain now than 20 years ago?
* How many different countries (states, counties, cities, etc) have records in this data set?

## Use SQL queries to pull specific information

Like with the Chinook data base, do NOT pull all the data and then filter using DataFrame methods etc.

Write your question and then answer it using the SQL statements below.  Be sure to use guardrails ( e.g. dryrun ).

##GOAL

 which is the country with the most purchases of music? and what are the complaints of those countries to better optimize top country satisfaction? will be looking joining and discecting invoices,  invoice_items, customers

In [1]:
# which is the country with the most purchases of music? and what are the complaints of those countries to better optimize top country satisfaction? will be looking joining and discecting invoices and invoice_items

In [ ]:
# will possibly also need to add on another thing

In [2]:
import sqlite3 as db
import pandas as pd

In [3]:
%%capture
%%bash
apt-get update
apt-get install -y sqlite3

In [4]:
!sqlite3 --version

3.37.2 2022-01-06 13:25:41 872ba256cbf61d9290b571c0e6d82a20c224ca3ad82971edc46b29818d5dalt1

In [5]:
%%bash
[ -f chinook.zip ] ||
  curl -s -O https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip
unzip -l chinook.zip

Archive:  chinook.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
   884736  2015-11-29 10:53   chinook.db
---------                     -------
   884736                     1 file

In [6]:
!unzip -u chinook.zip

Archive:  chinook.zip
  inflating: chinook.db

In [7]:
!ls -la

total 1180
drwxr-xr-x 1 root root   4096 Jul  7 16:01 .
drwxr-xr-x 1 root root   4096 Jul  7 15:47 ..
-rw-r--r-- 1 root root 884736 Nov 29  2015 chinook.db
-rw-r--r-- 1 root root 305596 Jul  7 16:01 chinook.zip
drwxr-xr-x 4 root root   4096 Jun  4 13:32 .config
drwxr-xr-x 1 root root   4096 Jun  4 13:32 sample_data

In [8]:
db_con = db.connect("chinook.db")
tables = pd.read_sql_query( query , db_con)

tables

     InvoiceLineId  InvoiceId  TrackId  UnitPrice  Quantity
0              468         87     2820       1.99         1
1              469         88     2826       1.99         1
2              470         88     2832       1.99         1
3              471         88     2838       1.99         1
4              472         88     2844       1.99         1
..             ...        ...      ...        ...       ...
106           2197        404     2895       1.99         1
107           2198        404     2904       1.99         1
108           2199        404     2913       1.99         1
109           2200        404     2922       1.99         1
110           2240        412     3177       1.99         1

[111 rows x 5 columns]

In [18]:
table_names_query = "SELECT name FROM sqlite_schema WHERE type='table';"
table_list = pd.read_sql_query(table_names_query, db_con)['name'].tolist()

print("--- Table Row Counts ---")

for table_name in table_list:
    count_query = f"SELECT COUNT(*) AS total_rows FROM [{table_name}]"
    count_df = pd.read_sql_query(count_query, db_con)
    row_count = count_df.iloc[0]['total_rows']

    print(f"Table: {table_name:<20} | Rows: {row_count}")

--- Table Row Counts ---
Table: albums               | Rows: 347
Table: sqlite_sequence      | Rows: 10
Table: artists              | Rows: 275
Table: customers            | Rows: 59
Table: employees            | Rows: 8
Table: genres               | Rows: 25
Table: invoices             | Rows: 412
Table: invoice_items        | Rows: 2240
Table: media_types          | Rows: 5
Table: playlists            | Rows: 18
Table: playlist_track       | Rows: 8715
Table: tracks               | Rows: 3503
Table: sqlite_stat1         | Rows: 15

### Basic Queries

#### SELECT (with * and with column names)

In [9]:
query = '''
  SELECT *
  FROM invoice_items


'''

artist = pd.read_sql_query(query, db_con)
artist

      InvoiceLineId  InvoiceId  TrackId  UnitPrice  Quantity
0                 1          1        2       0.99         1
1                 2          1        4       0.99         1
2                 3          2        6       0.99         1
3                 4          2        8       0.99         1
4                 5          2       10       0.99         1
...             ...        ...      ...        ...       ...
2235           2236        411     3136       0.99         1
2236           2237        411     3145       0.99         1
2237           2238        411     3154       0.99         1
2238           2239        411     3163       0.99         1
2239           2240        412     3177       1.99         1

[2240 rows x 5 columns]

#### WHERE

In [10]:
query = '''
  SELECT *
  FROM invoice_items
  WHERE UnitPrice >= 1.99

'''

artist = pd.read_sql_query(query, db_con)
artist

     InvoiceLineId  InvoiceId  TrackId  UnitPrice  Quantity
0              468         87     2820       1.99         1
1              469         88     2826       1.99         1
2              470         88     2832       1.99         1
3              471         88     2838       1.99         1
4              472         88     2844       1.99         1
..             ...        ...      ...        ...       ...
106           2197        404     2895       1.99         1
107           2198        404     2904       1.99         1
108           2199        404     2913       1.99         1
109           2200        404     2922       1.99         1
110           2240        412     3177       1.99         1

[111 rows x 5 columns]

In [ ]:
# there are 2 different price rannges 0.99 and 1.99 verified by adjusting the WHERE
# what determines the price of 1.99 and 0.99

#### AND

In [ ]:
query = '''
  SELECT *
  FROM invoices

'''

invoices_s = pd.read_sql_query(query, db_con)
invoices_s

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98
1,2,4,2009-01-02 00:00:00,Ullevålsveien 14,Oslo,None,Norway,0171,3.96
2,3,8,2009-01-03 00:00:00,Grétrystraat 63,Brussels,None,Belgium,1000,5.94
3,4,14,2009-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
4,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86
...,...,...,...,...,...,...,...,...,...
407,408,25,2013-12-05 00:00:00,319 N. Frances Street,Madison,WI,USA,53703,3.96
408,409,29,2013-12-06 00:00:00,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,5.94
409,410,35,2013-12-09 00:00:00,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,8.91
410,411,44,2013-12-14 00:00:00,Porthaninkatu 9,Helsinki,None,Finland,00530,13.86
411,412,58,2013-12-22 00:00:00,"12,Community Centre",Delhi,None,India,110017,1.99

In [ ]:
query = '''
  SELECT *
  FROM invoices
  WHERE BillingCountry = 'Germany'
'''

invoices_s = pd.read_sql_query(query, db_con)
invoices_s

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98
1,6,37,2009-01-19 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,0.99
2,7,38,2009-02-01 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,1.98
3,12,2,2009-02-11 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,13.86
4,29,36,2009-05-05 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,1.98
5,30,38,2009-05-06 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,3.96
6,40,36,2009-06-15 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,13.86
7,52,38,2009-08-08 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,5.94
8,67,2,2009-10-12 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,8.91
9,95,36,2010-02-13 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,8.91
10,104,38,2010-03-29 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,0.99
11,127,37,2010-07-13 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,1.98
12,138,37,2010-08-23 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,13.86
13,193,37,2011-04-23 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,14.91
14,196,2,2011-05-19 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,1.98
15,219,2,2011-08-21 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,3.96
16,224,36,2011-09-20 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,1.98
17,225,38,2011-09-20 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,1.98
18,236,38,2011-10-31 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,13.86
19,241,2,2011-11-23 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,5.94
20,247,36,2011-12-23 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,3.96
21,269,36,2012-03-26 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,5.94
22,291,38,2012-06-30 00:00:00,Barbarossastraße 19,Berlin,None,Germany,10779,8.91
23,293,2,2012-07-13 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,0.99
24,321,36,2012-11-14 00:00:00,Tauentzienstraße 8,Berlin,None,Germany,10789,0.99
25,322,37,2012-11-27 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,1.98
26,345,37,2013-03-01 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,3.96
27,367,37,2013-06-03 00:00:00,Berger Straße 10,Frankfurt,None,Germany,60316,5.94

In [ ]:
# trying to know how many countries have purchased/billed
query = '''
  SELECT COUNT(DISTINCT Billingcountry) AS unique_count
FROM invoices;
'''

invoices_s = pd.read_sql_query(query, db_con)
invoices_s

   unique_count
0            24

In [ ]:
query = '''
  SELECT DISTINCT Billingcountry
FROM invoices;
'''

invoices_s = pd.read_sql_query(query, db_con)
invoices_s

    BillingCountry
0          Germany
1           Norway
2          Belgium
3           Canada
4              USA
5           France
6          Ireland
7   United Kingdom
8        Australia
9            Chile
10           India
11          Brazil
12        Portugal
13     Netherlands
14           Spain
15          Sweden
16  Czech Republic
17         Finland
18         Denmark
19           Italy
20          Poland
21         Austria
22         Hungary
23       Argentina

In [ ]:
# I would like to add a column with the totals to see what country purchases more

In [13]:
# im gonna find out if there are them same amount of customers in both invoices and invoice_items
query = '''
  SELECT COUNT(DISTINCT CustomerId) AS how_md_customers
FROM invoices;
'''

invoices_s = pd.read_sql_query(query, db_con)
invoices_s

   how_md_customers
0                59

In [19]:
#seems like to me that the invoices relates to customers. the unique characters of
query = '''
  SELECT COUNT(DISTINCT CustomerId) AS how_md_customers
FROM customers;
'''

invoices_s = pd.read_sql_query(query, db_con)
invoices_s

   how_md_customers
0                59

In [17]:
query = '''
  SELECT COUNT(DISTINCT InvoiceId) AS how_md_customers
FROM invoice_items;
'''

invoices_s = pd.read_sql_query(query, db_con)
invoices_s

   how_md_customers
0               412

In [ ]:
# they dont match but the amount of unique customers in invoice_items equals the

#### OR

#### LIKE (with % or _ wildcard)

#### BETWEEN

#### LIMIT

### Sorting and Grouping

#### ORDER BY

#### DISTINCT

#### GROUP BY

### Aggregates

#### MAX

#### MIN

#### SUM

#### AVG

#### COUNT

## Make some plots

Make some cool plots to go with your data. Write SQL queries to get ONLY the information you need for each plot. (Don't pull ALL the data and then just plot a few columns.)

## EXTRA CREDIT:

#### Use a query that joins two tables.

#### Make a model to see if you can predict something

#### Come up with something else cool to do with your data