# Playing with NumPY

## Setup: Import numpy

In [6]:
import numpy as np
import pandas as pd

## Problem 1: random integers

### Part 1

Create a 1 dimensional array with 10 random integers

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Part 2

Create a second 1 dimensional array with 10 random integers.  Concatenate it with your first array to create a 2 dimensional array with shape (2,10).

**Note:**  You may have to get creative to make this work.

In [3]:
arr_2 = np.random.randint([1,2,3,4,5,6,7,8,9,10])
arr_2

array([0, 0, 1, 3, 4, 2, 0, 2, 5, 5])

In [46]:
arr_3 = np.random.random(10)
arr_3

array([0.34843202, 0.54223686, 0.89163938, 0.59710953, 0.6390056 ,
       0.12677928, 0.52478723, 0.69309095, 0.53729648, 0.40788904])

In [8]:
table_arr = pd.DataFrame(arr_2 + arr)
table_arr

    0
0   1
1   2
2   4
3   7
4   9
5   8
6   7
7  10
8  14
9  15

### Part 3

Use indexing to access the first two columns in the array you created in #2.

In [13]:
table_arr[:2]

   0
0  1
1  2

## Problem 2: 2D array

Convert the array below into a 2 dimensional array

```python
arr = np.arange(70)
```

In [15]:
arr = np.arange(70)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69])

In [36]:
arr_d = arr.reshape(7,10)
arr_d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

## Problem 3: multiply

Multiply all numbers in the array below by a number of your choice.

```python
arr = np.arange(30)
```

In [37]:
arr = np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [38]:
arr*5

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145])

## Problem 4: stats

Find the min, max, mean, sample standard deviation, and population standard deviation for the array below.

```python
arr = np.random.normal(5,10,10000)
```

In [40]:
arr = np.random.normal(5,10,10000)
arr

array([ 6.69116228e+00, -1.05935865e-03, -2.72159361e+00, ...,
        7.91636891e+00,  1.92385450e+01,  8.45605637e+00])

In [41]:
np.mean(arr)

np.float64(4.90567746445174)

In [42]:
np.min(arr)

np.float64(-35.52795102175372)

In [43]:
np.max(arr)

np.float64(42.12205549316052)

In [47]:
np.std(arr)

np.float64(10.04028341509324)

## Problem 5: filtering

### Part 1

Create a 4X6 array with random integers between 0 and 10.

In [53]:
arr_4 = np.random.randint(0, 10, (4,6))
arr_4

array([[8, 3, 3, 3, 4, 1],
       [4, 3, 7, 0, 0, 4],
       [4, 4, 9, 7, 2, 9],
       [7, 1, 3, 8, 3, 6]])

### Part 2

Create a boolean array with `True` entries where the entries in your array are greater than 6

In [54]:
filter = ( arr_4 > 6 )
filter.reshape(4,6)

array([[ True, False, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False,  True,  True, False,  True],
       [ True, False, False,  True, False, False]])

### Part 3

Use your boolean array as a filter to pull out the entries greater than 6

In [56]:
arr_4[filter]

array([8, 7, 9, 7, 9, 7, 8])

Numpy has many functions and methods.  Explore them to see what they do.

- [numpy at w3school]( https://www.w3schools.com/python/numpy/default.asp )
- [numpy at numpy.org]( https://numpy.org/doc/2.2/user/quickstart.html )
- [blog at medium.com]( https://medium.com/@brusooo27/40-most-used-numpy-methods-c2e3ed2018d4 )